name: discord
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.9=h2bbff1b_0
  - pip=23.2.1=py311haa95532_0
  - python=3.11.4=he1021f5_0
  - setuptools=68.0.0=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py311haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - asgiref==3.7.2
      - async-timeout==4.0.2
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - colorama==0.4.6
      - django==4.2.4
      - django-cors-headers==4.2.0
      - djangorestframework==3.14.0
      - frozenlist==1.4.0
      - idna==3.4
      - multidict==6.0.4
      - openai==0.27.8
      - python-dotenv==1.0.0
      - pytz==2023.3
      - requests==2.31.0
      - sqlparse==0.4.4
      - tqdm==4.65.0
      - tzdata==2023.3
      - urllib3==2.0.4
      - yarl==1.9.2
prefix: D:\miniconda3\envs\discord
